# Turns every MiniTest TEST_CASE into its own ctest entry.
#
# Runs the freshly built test binary with --list-tests and writes an
# add_test() call per case. This is the MiniTest equivalent of Catch2's
# catch_discover_tests(): a red CI names the case that died, and
# `ctest -R "cancel"` selects individual cases.
#
# Expected cache entries: TEST_EXECUTABLE, CTEST_FILE, TEST_PREFIX.

execute_process(
    COMMAND "${TEST_EXECUTABLE}" --list-tests
    OUTPUT_VARIABLE discovered_output
    RESULT_VARIABLE discovery_result
    ERROR_VARIABLE discovery_error
)

if(NOT discovery_result EQUAL 0)
    message(FATAL_ERROR
        "Failed to list tests from ${TEST_EXECUTABLE}: ${discovery_error}")
endif()

# Case names may contain semicolons, which are CMake's list separator. Escape
# them before splitting on newlines, then restore them per line, so a name like
# "warms empty state; clear at start is delivered" stays one test.
string(REPLACE ";" "\\;" discovered_output "${discovered_output}")
string(REPLACE "\n" ";" discovered_lines "${discovered_output}")

set(generated "# Generated by DiscoverMiniTests.cmake. Do not edit.\n")
foreach(line IN LISTS discovered_lines)
    string(REPLACE "\\;" ";" line "${line}")
    string(STRIP "${line}" case_name)
    if(case_name STREQUAL "")
        continue()
    endif()
    # Escape characters that would break the generated add_test() call.
    string(REPLACE "\\" "\\\\" escaped "${case_name}")
    string(REPLACE "\"" "\\\"" escaped "${escaped}")
    # CTest reads this file with its own limited parser, which only accepts the
    # positional add_test(<name> <command> <args...>) signature. The
    # NAME/COMMAND keyword form is a CMake-only spelling and is silently
    # mis-parsed here.
    string(APPEND generated
        "add_test(\"${TEST_PREFIX}${escaped}\""
        " \"${TEST_EXECUTABLE}\" \"${escaped}\")\n")
endforeach()

file(WRITE "${CTEST_FILE}" "${generated}")
